"""remove_slo

Revision ID: 22a076a0794f
Revises: a031a37ce81d
Create Date: 2017-08-18 11:00:46.904991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22a076a0794f'
down_revision = 'a031a37ce81d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_attribute_slo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_attribute_slo',
    sa.Column('datacenter_name', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('sensor_attribute_name', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('min_threshold', mysql.FLOAT(), nullable=True),
    sa.Column('max_threshold', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['datacenter_name', 'sensor_attribute_name'], [u'sensor_attribute.datacenter_name', u'sensor_attribute.name'], name=u'sensor_attribute_slo_ibfk_1', onupdate=u'CASCADE', ondelete=u'CASCADE'),
    sa.ForeignKeyConstraint(['datacenter_name'], [u'datacenter.name'], name=u'sensor_attribute_slo_ibfk_2', onupdate=u'CASCADE', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'sensor_attribute_name'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
