"""add_differentiation

Revision ID: 5e39b15afd90
Revises: 22a076a0794f
Create Date: 2017-08-18 15:17:56.159872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e39b15afd90'
down_revision = '22a076a0794f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller_parameter', sa.Column('differentiation_max', sa.Float(), nullable=True))
    op.add_column('controller_parameter', sa.Column('differentiation_min', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controller_parameter', 'differentiation_min')
    op.drop_column('controller_parameter', 'differentiation_max')
    # ### end Alembic commands ###
