"""add_name_pattern

Revision ID: 7a4549aae66a
Revises: 20c4b8156f4f
Create Date: 2017-08-02 22:39:00.369411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a4549aae66a'
down_revision = '20c4b8156f4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('energy_optimazation_target')
    op.add_column('controller_attribute', sa.Column('measurement_pattern', sa.String(length=256), nullable=True))
    op.add_column('controller_power_supply_attribute', sa.Column('measurement_pattern', sa.String(length=256), nullable=True))
    op.add_column('environment_sensor_attribute', sa.Column('measurement_pattern', sa.String(length=256), nullable=True))
    op.add_column('power_supply_attribute', sa.Column('measurement_pattern', sa.String(length=256), nullable=True))
    op.add_column('sensor_attribute', sa.Column('measurement_pattern', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_attribute', 'measurement_pattern')
    op.drop_column('power_supply_attribute', 'measurement_pattern')
    op.drop_column('environment_sensor_attribute', 'measurement_pattern')
    op.drop_column('controller_power_supply_attribute', 'measurement_pattern')
    op.drop_column('controller_attribute', 'measurement_pattern')
    op.create_table('energy_optimazation_target',
    sa.Column('type', mysql.ENUM(u'binary', u'continuous', u'integer', u'discrete'), server_default=sa.text(u"'continuous'"), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('mean', mysql.FLOAT(), nullable=True),
    sa.Column('deviation', mysql.FLOAT(), nullable=True),
    sa.Column('max', mysql.FLOAT(), nullable=True),
    sa.Column('min', mysql.FLOAT(), nullable=True),
    sa.Column('differentiation_mean', mysql.FLOAT(), nullable=True),
    sa.Column('differentiation_deviation', mysql.FLOAT(), nullable=True),
    sa.Column('differentiation_max', mysql.FLOAT(), nullable=True),
    sa.Column('differentiation_min', mysql.FLOAT(), nullable=True),
    sa.Column('possible_values', mysql.JSON(), nullable=True),
    sa.Column('datacenter_name', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('properties', mysql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['datacenter_name'], [u'datacenter.name'], name=u'energy_optimazation_target_ibfk_1', onupdate=u'CASCADE', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'name'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
