"""add_slo

Revision ID: 821e57bc5d7d
Revises: 65e726eb9e84
Create Date: 2017-07-07 01:14:56.392455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821e57bc5d7d'
down_revision = '65e726eb9e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_attribute_slo',
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('sensor_attribute_name', sa.String(length=36), nullable=False),
    sa.Column('min_threshold', sa.Float(), nullable=True),
    sa.Column('max_threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['datacenter_name', 'sensor_attribute_name'], ['sensor_attribute.datacenter_name', 'sensor_attribute.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'sensor_attribute_name')
    )
    op.drop_index('datacenter_name_2', table_name='controller_parameter_prediction')
    op.drop_index('datacenter_name_2', table_name='sensor_attribute_prediction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('datacenter_name_2', 'sensor_attribute_prediction', ['datacenter_name', 'sensor_name', 'sensor_attribute_name'], unique=False)
    op.create_index('datacenter_name_2', 'controller_parameter_prediction', ['datacenter_name', 'controller_parameter_name'], unique=False)
    op.drop_table('sensor_attribute_slo')
    # ### end Alembic commands ###
