"""init

Revision ID: 9a7e0d985b98
Revises: 
Create Date: 2017-07-04 21:31:49.185004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7e0d985b98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datacenter',
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('production', 'lab'), server_default='production', nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('sensor_attributes_prediction_model', sa.String(length=36), nullable=True),
    sa.Column('controller_attributes_prediction_model', sa.String(length=36), nullable=True),
    sa.Column('pue_prediction_model', sa.String(length=36), nullable=True),
    sa.Column('best_controller_params_model', sa.String(length=36), nullable=True),
    sa.Column('decision_model', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('controller',
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'name')
    )
    op.create_table('controller_attribute',
    sa.Column('type', sa.Enum('binary', 'continuous', 'integer', 'discrete'), server_default='continuous', nullable=True),
    sa.Column('unit', sa.String(length=36), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('possible_values', sa.JSON(), nullable=True),
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'name')
    )
    op.create_table('controller_parameter',
    sa.Column('type', sa.Enum('binary', 'continuous', 'integer', 'discrete'), server_default='continuous', nullable=True),
    sa.Column('unit', sa.String(length=36), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('possible_values', sa.JSON(), nullable=True),
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'name')
    )
    op.create_table('environment_sensor',
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'name')
    )
    op.create_table('environment_sensor_attribute',
    sa.Column('type', sa.Enum('binary', 'continuous', 'integer', 'discrete'), server_default='continuous', nullable=True),
    sa.Column('unit', sa.String(length=36), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('possible_values', sa.JSON(), nullable=True),
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'name')
    )
    op.create_table('sensor',
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'name')
    )
    op.create_table('sensor_attribute',
    sa.Column('type', sa.Enum('binary', 'continuous', 'integer', 'discrete'), server_default='continuous', nullable=True),
    sa.Column('unit', sa.String(length=36), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('possible_values', sa.JSON(), nullable=True),
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'name')
    )
    op.create_table('controller_attribute_data',
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('controller_name', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['datacenter_name', 'controller_name'], ['controller.datacenter_name', 'controller.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['datacenter_name', 'name'], ['controller_attribute.datacenter_name', 'controller_attribute.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'controller_name', 'name')
    )
    op.create_table('controller_parameter_data',
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('controller_name', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['datacenter_name', 'controller_name'], ['controller.datacenter_name', 'controller.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['datacenter_name', 'name'], ['controller_parameter.datacenter_name', 'controller_parameter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'controller_name', 'name')
    )
    op.create_table('environment_sensor_attribute_data',
    sa.Column('type', sa.Enum('binary', 'continuous', 'integer', 'discrete'), server_default='continuous', nullable=True),
    sa.Column('unit', sa.String(length=36), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('possible_values', sa.JSON(), nullable=True),
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('environment_sensor_name', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['datacenter_name', 'environment_sensor_name'], ['environment_sensor.datacenter_name', 'environment_sensor.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['datacenter_name', 'name'], ['environment_sensor_attribute.datacenter_name', 'environment_sensor_attribute.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'environment_sensor_name', 'name')
    )
    op.create_table('sensor_attribute_data',
    sa.Column('datacenter_name', sa.String(length=36), nullable=False),
    sa.Column('sensor_name', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['datacenter_name', 'name'], ['sensor_attribute.datacenter_name', 'sensor_attribute.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['datacenter_name', 'sensor_name'], ['sensor.datacenter_name', 'sensor.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['datacenter_name'], ['datacenter.name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('datacenter_name', 'sensor_name', 'name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_attribute_data')
    op.drop_table('environment_sensor_attribute_data')
    op.drop_table('controller_parameter_data')
    op.drop_table('controller_attribute_data')
    op.drop_table('sensor_attribute')
    op.drop_table('sensor')
    op.drop_table('environment_sensor_attribute')
    op.drop_table('environment_sensor')
    op.drop_table('controller_parameter')
    op.drop_table('controller_attribute')
    op.drop_table('controller')
    op.drop_table('datacenter')
    # ### end Alembic commands ###
