#!/bin/bash
#
# energy-saving-celeryd          Energy saving celeryd daemon
##################################

# LSB header

### BEGIN INIT INFO
# Provides: energy-saving-celeryd
# Required-Start: $networking $apache2
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: energy saving celeryd
# Description: energy saving celery daemon service
#              
### END INIT INFO
DEBIAN=/etc/debian_version
SUSE=/etc/SuSE-release
CELERY=`which celery`

if [ -f $DEBIAN ]; then
    . /lib/lsb/init-functions
elif [ -f $SUSE -a -r /etc/rc.status ]; then
    . /etc/rc.status
else
    . /etc/rc.d/init.d/functions
fi

RETVAL=0
start() {
    echo -n "Starting energy saving Celeryd: "
    if [ -f $SUSE ]; then
        startproc -f -p /var/run/celery-worker.pid -l /tmp/celery-worker.log "C_FORCE_ROOT=1 CELERY_CONFIG_MODULE=energy_saving.utils.celeryconfig $CELERY worker"
        rc_status -v
        RETVAL=$?
    elif [ -f $DEBIAN ]; then
        start_daemon -p /var/run/celery-worker.pid "C_FORCE_ROOT=1 CELERY_CONFIG_MODULE=energy_saving.utils.celeryconfig $CELERY worker &>/tmp/celery-worker.log & echo \$!> /var/run/celery-worker.pid"
        RETVAL=$?
    else
        daemon --pidfile /var/run/celery-worker.pid "C_FORCE_ROOT=1 CELERY_CONFIG_MODULE=energy_saving.utils.celeryconfig $CELERY worker &>/tmp/celery-worker.log & echo \$! > /var/run/celery-worker.pid"
        RETVAL=$?
    fi
    echo
    retries=0
    max_retries=10
    output=''
    while [ $retries -lt $max_retries ]; do
      output=$(C_FORCE_ROOT=1 CELERY_CONFIG_MODULE=energy_saving.utils.celeryconfig $CELERY status 2&>1)
      RETVAL=$?
      if [ "$RETVAL" == "0" ]; then
          break
      else
          sleep 10
      fi
      let retries=${retries}+1
    done
    if [ "$RETVAL" != "0" ]; then
        echo $output
    fi
    return $RETVAL
}

stop() {
    echo -n "Stopping energy saving Celeryd: "
    if [ -f $SUSE ]; then
        killproc -t 10 -p /var/run/celery-worker.pid $CELERY
        rc_status -v
        RETVAL=$?
    elif [ -f $DEBIAN ]; then
        killproc -p /var/run/celery-worker.pid $CELERY -TERM
        RETVAL=$?
    else
        killproc -p /var/run/celery-worker.pid -d 30 $CELERY
        RETVAL=$?
    fi
    echo
}

restart() {
   stop
   start
}

case "$1" in
    start|stop|restart)
        $1
        ;;
    status)
        echo -n "Checking energy saving celeryd: "
        if [ -f $SUSE ]; then
            checkproc -v -p /var/run/celery-worker.pid $CELERY
            rc_status -v
            RETVAL=$?
        elif [ -f $DEBIAN ]; then
            status_of_proc -p /var/run/celery-worker.pid $CELERY
            RETVAL=$?
        else
            status -p /var/run/celery-worker.pid $CELERY
            RETVAL=$?
        fi
        if [ "$RETVAL" == "0" ]; then
            C_FORCE_ROOT=1 CELERY_CONFIG_MODULE=energy_saving.utils.celeryconfig $CELERY status
            RETVAL=$?
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
